name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: 6.0.119
  CODE_ANALYSIS_DOTNET_VERSION: 3.1.x

jobs:
  static_code_analysis:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION }}
            ${{ env.CODE_ANALYSIS_DOTNET_VERSION }}
          global-json-file: cloud_connectors/azure/digital_twins_connector/global.json
      - name: Cache NuGet dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Build Digital Twins Connector
        run: ./cloud_connectors/azure/digital_twins_connector/build.sh
      - name: Build MQTT Connector's Azure Function
        run: dotnet build cloud_connectors/azure/mqtt_connector/azure_function/src/function.csproj
      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@main
        id: net-code-analysis
        with:
          projects: cloud_connectors/azure/digital_twins_connector/src/core/DigitalTwinsConnector.csproj;
            cloud_connectors/azure/digital_twins_connector/src/DigitalTwinsClientWrapper/DigitalTwinsClientWrapper.csproj;
            cloud_connectors/azure/digital_twins_connector/tests/DigitalTwinsClientWrapper.Tests/DigitalTwinsClientWrapper.Tests.csproj;
            cloud_connectors/azure/mqtt_connector/azure_function/src/function.csproj;
            cloud_connectors/azure/mqtt_connector/azure_function/tests/MQTTConnectorAzureFunction.Tests.csproj
          build-breaking: true
          all-categories: latest-recommended
      - name: Digital Twins Connector Tests
        run: dotnet test cloud_connectors/azure/digital_twins_connector/tests/**/*.csproj
      - name: MQTT Connector's Azure Function Tests
        run: dotnet test cloud_connectors/azure/mqtt_connector/azure_function/tests/MQTTConnectorAzureFunction.Tests.csproj